---
version: "3.9"
services:
  app:
    build: .
    container_name: myapplicationContainer
    ports: 
      - "5000:80"
    depends_on:
      - db
    volumes:
      - myapplication:/App

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mystorageContainer  
    environment:
            SA_PASSWORD: "Welcome@123"
            ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    volumes: 
      - mystorage:/var/opt/mssql

volumes:
  mystorage:
  myapplication:

