// <auto-generated />
using System;
using JobManagerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobManagerAPI.Migrations
{
    [DbContext(typeof(JobManagerContext))]
    partial class JobManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobManagerAPI.Models.Bankdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Ifsc")
                        .HasColumnName("IFSC")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Bankdetails");
                });

            modelBuilder.Entity("JobManagerAPI.Models.MaterialTmp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("L")
                        .HasColumnType("float");

                    b.Property<string>("Material")
                        .HasColumnName("material")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("float");

                    b.Property<double?>("Smts")
                        .HasColumnName("smts")
                        .HasColumnType("float");

                    b.Property<double?>("SunitPrice")
                        .HasColumnName("Sunit_price")
                        .HasColumnType("float");

                    b.Property<double?>("TotalAmt")
                        .HasColumnName("total_amt")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Typeofmaterial")
                        .HasColumnName("typeofmaterial")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("UnitPrice")
                        .HasColumnName("unit_price")
                        .HasColumnType("float");

                    b.Property<string>("UnitType")
                        .HasColumnName("unit_type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Updatedby")
                        .HasColumnName("updatedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("W")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("material_tmp");
                });

            modelBuilder.Entity("JobManagerAPI.Models.PasteError", b =>
                {
                    b.Property<double?>("F1")
                        .HasColumnType("float");

                    b.Property<string>("F2")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("F3")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("F4")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("F5")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("F6")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.ToTable("Paste Errors");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Add1")
                        .HasColumnName("add1")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Add2")
                        .HasColumnName("add2")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_address");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblBagMstr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bag")
                        .HasColumnName("bag")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BagCode")
                        .HasColumnName("bag_code")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Image")
                        .HasColumnName("image")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_bag_MSTR");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblBalancePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Bal")
                        .HasColumnName("bal")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Baldate")
                        .HasColumnName("baldate")
                        .HasColumnType("datetime");

                    b.Property<string>("Mrnid")
                        .HasColumnName("MRNID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Paid")
                        .HasColumnName("paid")
                        .HasColumnType("float");

                    b.Property<string>("Suplier")
                        .HasColumnName("suplier")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Totalamt")
                        .HasColumnName("totalamt")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_balance_payments");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblBalanceSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("C1")
                        .HasColumnName("c1")
                        .HasColumnType("float");

                    b.Property<double?>("C10")
                        .HasColumnName("c10")
                        .HasColumnType("float");

                    b.Property<double?>("C2")
                        .HasColumnName("c2")
                        .HasColumnType("float");

                    b.Property<double?>("C3")
                        .HasColumnName("c3")
                        .HasColumnType("float");

                    b.Property<double?>("C4")
                        .HasColumnName("c4")
                        .HasColumnType("float");

                    b.Property<double?>("C5")
                        .HasColumnName("c5")
                        .HasColumnType("float");

                    b.Property<double?>("C6")
                        .HasColumnName("c6")
                        .HasColumnType("float");

                    b.Property<double?>("C7")
                        .HasColumnName("c7")
                        .HasColumnType("float");

                    b.Property<double?>("C8")
                        .HasColumnName("c8")
                        .HasColumnType("float");

                    b.Property<double?>("C9")
                        .HasColumnName("c9")
                        .HasColumnType("float");

                    b.Property<double?>("CTotal")
                        .HasColumnName("c_total")
                        .HasColumnType("float");

                    b.Property<double?>("D1")
                        .HasColumnName("d1")
                        .HasColumnType("float");

                    b.Property<double?>("D10")
                        .HasColumnName("d10")
                        .HasColumnType("float");

                    b.Property<double?>("D2")
                        .HasColumnName("d2")
                        .HasColumnType("float");

                    b.Property<double?>("D3")
                        .HasColumnName("d3")
                        .HasColumnType("float");

                    b.Property<double?>("D4")
                        .HasColumnName("d4")
                        .HasColumnType("float");

                    b.Property<double?>("D5")
                        .HasColumnName("d5")
                        .HasColumnType("float");

                    b.Property<double?>("D6")
                        .HasColumnName("d6")
                        .HasColumnType("float");

                    b.Property<double?>("D7")
                        .HasColumnName("d7")
                        .HasColumnType("float");

                    b.Property<double?>("D8")
                        .HasColumnName("d8")
                        .HasColumnType("float");

                    b.Property<double?>("D9")
                        .HasColumnName("d9")
                        .HasColumnType("float");

                    b.Property<double?>("DTotal")
                        .HasColumnName("d_total")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Datec")
                        .HasColumnName("datec")
                        .HasColumnType("datetime");

                    b.Property<string>("Particulars")
                        .HasColumnName("particulars")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Ref")
                        .HasColumnName("ref")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_BalanceSheet");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblCashbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("CAmount")
                        .HasColumnName("c_amount")
                        .HasColumnType("float");

                    b.Property<string>("CDetails")
                        .HasColumnName("c_details")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CParticulars")
                        .HasColumnName("c_particulars")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CRef")
                        .HasColumnName("c_ref")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("DAmount")
                        .HasColumnName("d_amount")
                        .HasColumnType("float");

                    b.Property<string>("DDetails")
                        .HasColumnName("d_details")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DParticulars")
                        .HasColumnName("d_particulars")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DRef")
                        .HasColumnName("d_ref")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Datec")
                        .HasColumnName("datec")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("tbl_cashbook");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aadhaar")
                        .HasColumnName("aadhaar")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Bank")
                        .HasColumnName("bank")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BankAcNo")
                        .HasColumnName("bankAcNo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Br")
                        .HasColumnName("BR")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Cid")
                        .HasColumnName("CID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasColumnName("contact_no")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Customer")
                        .HasColumnName("customer")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customerID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Gstno")
                        .HasColumnName("gstno")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Ifsc")
                        .HasColumnName("ifsc")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Pan")
                        .HasColumnName("pan")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PlaceCity")
                        .HasColumnName("place_city")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_customer");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("datetime");

                    b.Property<string>("Material")
                        .HasColumnName("material")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaterialType")
                        .HasColumnName("materialType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Mrnid")
                        .HasColumnName("MRNID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Remarks")
                        .HasColumnName("remarks")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_damages");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblDate", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.ToTable("tbl_date");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Doj")
                        .HasColumnName("DOJ")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Dor")
                        .HasColumnName("DOR")
                        .HasColumnType("datetime");

                    b.Property<int?>("EmpId")
                        .HasColumnName("EmpID")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Exist")
                        .HasColumnName("exist")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Salary")
                        .HasColumnName("salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_employees");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblEstimation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Balanceitems")
                        .HasColumnName("balanceitems")
                        .HasColumnType("float");

                    b.Property<string>("Closedby")
                        .HasColumnName("closedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Closedon")
                        .HasColumnName("closedon")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasColumnName("createdby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerId")
                        .HasColumnName("customerID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Item")
                        .HasColumnName("item")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Itemcode")
                        .HasColumnName("itemcode")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Itemcost")
                        .HasColumnName("itemcost")
                        .HasColumnType("float");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Jobcardno")
                        .HasColumnType("int");

                    b.Property<double?>("MaterialCost")
                        .HasColumnName("materialCost")
                        .HasColumnType("float");

                    b.Property<double?>("Mrp")
                        .HasColumnName("MRP")
                        .HasColumnType("float");

                    b.Property<double?>("Profit")
                        .HasColumnName("profit")
                        .HasColumnType("float");

                    b.Property<int?>("ProfitPer")
                        .HasColumnName("profit_per")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Totalamt")
                        .HasColumnName("totalamt")
                        .HasColumnType("float");

                    b.Property<double?>("TotalamtWop")
                        .HasColumnName("totalamtWOP")
                        .HasColumnType("float");

                    b.Property<double?>("Totalexp")
                        .HasColumnName("totalexp")
                        .HasColumnType("float");

                    b.Property<double?>("Totalitems")
                        .HasColumnName("totalitems")
                        .HasColumnType("float");

                    b.Property<double?>("Totallabchrg")
                        .HasColumnName("totallabchrg")
                        .HasColumnType("float");

                    b.Property<double?>("Westage")
                        .HasColumnName("westage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_estimation");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblEstimationProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cost")
                        .HasColumnName("cost")
                        .HasColumnType("float");

                    b.Property<double?>("Dayofwork")
                        .HasColumnName("dayofwork")
                        .HasColumnType("float");

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Jobtype")
                        .HasColumnName("jobtype")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Proddate")
                        .HasColumnName("proddate")
                        .HasColumnType("datetime");

                    b.Property<double?>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("float");

                    b.Property<int>("Uid")
                        .HasColumnName("UID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerId")
                        .HasColumnName("workerID")
                        .HasColumnType("int");

                    b.Property<string>("Workername")
                        .HasColumnName("workername")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_estimation_production");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblEstimationWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Material")
                        .HasColumnName("material")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("MaterialId")
                        .HasColumnName("materialID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialType")
                        .HasColumnName("materialType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Price")
                        .HasColumnName("price")
                        .HasColumnType("float");

                    b.Property<double?>("PricePerUnit")
                        .HasColumnName("price_per_unit")
                        .HasColumnType("float");

                    b.Property<double?>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("float");

                    b.Property<int>("Tid")
                        .HasColumnName("TID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("WorkerId")
                        .HasColumnName("workerID")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .HasColumnName("workerName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_estimation_workers");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblExpens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cheque")
                        .HasColumnName("cheque")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Expdate")
                        .HasColumnName("expdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Expense")
                        .HasColumnName("expense")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Particulars")
                        .HasColumnName("particulars")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Totalamt")
                        .HasColumnName("totalamt")
                        .HasColumnType("float");

                    b.Property<string>("Trantype")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Updatedby")
                        .HasColumnName("updatedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Updatedon")
                        .HasColumnName("updatedon")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("tbl_Expenses");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblExpenseMstr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExpenceType")
                        .HasColumnName("expenceType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Fileds")
                        .HasColumnName("fileds")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TransactionType")
                        .HasColumnName("transactionType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_Expense_MSTR");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Aftertax")
                        .HasColumnName("aftertax")
                        .HasColumnType("float");

                    b.Property<double?>("Balance")
                        .HasColumnName("balance")
                        .HasColumnType("float");

                    b.Property<double?>("Cgst")
                        .HasColumnName("CGST")
                        .HasColumnType("float");

                    b.Property<double?>("Cgstp")
                        .HasColumnName("CGSTP")
                        .HasColumnType("float");

                    b.Property<string>("CustomerId")
                        .HasColumnName("customerID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Igst")
                        .HasColumnName("IGST")
                        .HasColumnType("float");

                    b.Property<double?>("Igstp")
                        .HasColumnName("IGSTP")
                        .HasColumnType("float");

                    b.Property<string>("Invoice")
                        .HasColumnName("invoice")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("InvoiceId")
                        .HasColumnName("invoiceID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Invoicedate")
                        .HasColumnName("invoicedate")
                        .HasColumnType("datetime");

                    b.Property<double?>("Misc")
                        .HasColumnName("MISC")
                        .HasColumnType("float");

                    b.Property<double?>("Paidamt")
                        .HasColumnName("paidamt")
                        .HasColumnType("float");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Roundamount")
                        .HasColumnName("roundamount")
                        .HasColumnType("float");

                    b.Property<double?>("Sgst")
                        .HasColumnName("SGST")
                        .HasColumnType("float");

                    b.Property<double?>("Sgstp")
                        .HasColumnName("SGSTP")
                        .HasColumnType("float");

                    b.Property<DateTime?>("SupplyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SupplyPlace")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Totalamt")
                        .HasColumnName("totalamt")
                        .HasColumnType("float");

                    b.Property<string>("Tranno")
                        .HasColumnName("tranno")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Transport")
                        .HasColumnName("transport")
                        .HasColumnType("float");

                    b.Property<string>("TransportMode")
                        .HasColumnName("Transport_mode")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Updatedby")
                        .HasColumnName("updatedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Updatedon")
                        .HasColumnName("updatedon")
                        .HasColumnType("datetime");

                    b.Property<string>("VechicleNumber")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_invoice");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("float");

                    b.Property<string>("Invoice")
                        .HasColumnName("invoice")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Item")
                        .HasColumnName("item")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Itemcode")
                        .HasColumnName("itemcode")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Itemcost")
                        .HasColumnName("itemcost")
                        .HasColumnType("float");

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Jobtype")
                        .HasColumnName("jobtype")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaterialType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Totalitems")
                        .HasColumnName("totalitems")
                        .HasColumnType("float");

                    b.Property<string>("Updatedby")
                        .HasColumnName("updatedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Wid")
                        .HasColumnName("wid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_invoice_items");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblJobcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Balanceitems")
                        .HasColumnName("balanceitems")
                        .HasColumnType("float");

                    b.Property<string>("Closedby")
                        .HasColumnName("closedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Closedon")
                        .HasColumnName("closedon")
                        .HasColumnType("datetime");

                    b.Property<string>("Createdby")
                        .HasColumnName("createdby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Createdon")
                        .HasColumnName("createdon")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerId")
                        .HasColumnName("customerID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Damages")
                        .HasColumnName("damages")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Expected")
                        .HasColumnName("expected")
                        .HasColumnType("datetime");

                    b.Property<string>("Item")
                        .HasColumnName("item")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Itemcode")
                        .HasColumnName("itemcode")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Itemcost")
                        .HasColumnName("itemcost")
                        .HasColumnType("float");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Jobcardno")
                        .HasColumnType("int");

                    b.Property<double?>("MaterialCost")
                        .HasColumnName("materialCost")
                        .HasColumnType("float");

                    b.Property<double?>("Mrp")
                        .HasColumnName("MRP")
                        .HasColumnType("float");

                    b.Property<double?>("Profit")
                        .HasColumnName("profit")
                        .HasColumnType("float");

                    b.Property<int?>("ProfitPer")
                        .HasColumnName("profit_per")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Totalamt")
                        .HasColumnName("totalamt")
                        .HasColumnType("float");

                    b.Property<double?>("TotalamtWop")
                        .HasColumnName("totalamtWOP")
                        .HasColumnType("float");

                    b.Property<double?>("Totalexp")
                        .HasColumnName("totalexp")
                        .HasColumnType("float");

                    b.Property<double?>("Totalitems")
                        .HasColumnName("totalitems")
                        .HasColumnType("float");

                    b.Property<double?>("Totallabchrg")
                        .HasColumnName("totallabchrg")
                        .HasColumnType("float");

                    b.Property<double?>("Westage")
                        .HasColumnName("westage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_jobcards");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblJobcardsWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Material")
                        .HasColumnName("material")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("MaterialId")
                        .HasColumnName("materialID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialType")
                        .HasColumnName("materialType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Price")
                        .HasColumnName("price")
                        .HasColumnType("float");

                    b.Property<double?>("PricePerUnit")
                        .HasColumnName("price_per_unit")
                        .HasColumnType("float");

                    b.Property<double?>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("UnitType")
                        .HasColumnName("unit_type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("WorkerId")
                        .HasColumnName("workerID")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .HasColumnName("workerName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_jobcards_workers");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Imgpath")
                        .HasColumnName("imgpath")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_materials");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblMrn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BalQty")
                        .HasColumnName("bal_qty")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BillInvoiceDate")
                        .HasColumnName("bill_invoice_date")
                        .HasColumnType("datetime");

                    b.Property<string>("BillInvoiceNo")
                        .HasColumnName("bill_invoice_no")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Damages")
                        .HasColumnName("damages")
                        .HasColumnType("float");

                    b.Property<double?>("L")
                        .HasColumnType("float");

                    b.Property<string>("Material")
                        .HasColumnName("material")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("MaterialId")
                        .HasColumnName("materialID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialType")
                        .HasColumnName("materialType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Mrnid")
                        .HasColumnName("MRNID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Mrp")
                        .HasColumnName("MRP")
                        .HasColumnType("float");

                    b.Property<double?>("PricePerUnit")
                        .HasColumnName("price_per_unit")
                        .HasColumnType("float");

                    b.Property<double?>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("float");

                    b.Property<string>("Remarks")
                        .HasColumnName("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Smts")
                        .HasColumnName("smts")
                        .HasColumnType("float");

                    b.Property<double?>("SunitPrice")
                        .HasColumnName("Sunit_price")
                        .HasColumnType("float");

                    b.Property<double?>("TotalAmt")
                        .HasColumnName("total_amt")
                        .HasColumnType("float");

                    b.Property<double?>("TranceportCharge")
                        .HasColumnName("tranceport_charge")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("UnitType")
                        .HasColumnName("unit_type")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Updatedby")
                        .HasColumnName("updatedby")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Updatedon")
                        .HasColumnName("updatedon")
                        .HasColumnType("datetime");

                    b.Property<double?>("W")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_MRN");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblMrnMstr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BalAmt")
                        .HasColumnName("bal_amt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BillInvoiceDate")
                        .HasColumnName("bill_invoice_date")
                        .HasColumnType("datetime");

                    b.Property<string>("BillInvoiceNo")
                        .HasColumnName("bill_invoice_no")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("InvoiceAmt")
                        .HasColumnName("invoice_amt")
                        .HasColumnType("float");

                    b.Property<double?>("MiscAmt")
                        .HasColumnName("misc_amt")
                        .HasColumnType("float");

                    b.Property<int?>("Mrn")
                        .HasColumnName("MRN")
                        .HasColumnType("int");

                    b.Property<string>("Mrnid")
                        .HasColumnName("MRNID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("PaidAmt")
                        .HasColumnName("paid_amt")
                        .HasColumnType("float");

                    b.Property<string>("PaymentMode")
                        .HasColumnName("payment_mode")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Remarks")
                        .HasColumnName("remarks")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("SuplierId")
                        .HasColumnName("SuplierID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("TotalAmt")
                        .HasColumnName("total_amt")
                        .HasColumnType("int");

                    b.Property<string>("TranNo")
                        .HasColumnName("tran_no")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("TranceportCharge")
                        .HasColumnName("tranceport_charge")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tbl_MRN_MSTR");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblProdType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductionType")
                        .IsRequired()
                        .HasColumnName("productionType")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_prodType");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Dayofwork")
                        .HasColumnName("dayofwork")
                        .HasColumnType("float");

                    b.Property<string>("JobcardId")
                        .HasColumnName("JobcardID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Jobtype")
                        .HasColumnName("jobtype")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("Proddate")
                        .HasColumnName("proddate")
                        .HasColumnType("datetime");

                    b.Property<double?>("Qty")
                        .HasColumnName("qty")
                        .HasColumnType("float");

                    b.Property<int?>("WorkerId")
                        .HasColumnName("workerID")
                        .HasColumnType("int");

                    b.Property<string>("Workername")
                        .HasColumnName("workername")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_production");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblSuplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aadhaar")
                        .HasColumnName("aadhaar")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Bank")
                        .HasColumnName("bank")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("BankAcNo")
                        .HasColumnName("bankAcNo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Br")
                        .HasColumnName("BR")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Branch")
                        .HasColumnName("branch")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ContactNo")
                        .HasColumnName("contact_no")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Gstno")
                        .HasColumnName("gstno")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Ifsc")
                        .HasColumnName("ifsc")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Pan")
                        .HasColumnName("pan")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PlaceCity")
                        .HasColumnName("place_city")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Sid")
                        .HasColumnName("SID")
                        .HasColumnType("int");

                    b.Property<string>("Suplier")
                        .HasColumnName("suplier")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("SuplierId")
                        .IsRequired()
                        .HasColumnName("SuplierID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TinNo")
                        .HasColumnName("tin_no")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_suplier");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessLevel")
                        .HasColumnName("accessLevel")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .HasColumnName("userID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnName("userName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("tbl_users");
                });

            modelBuilder.Entity("JobManagerAPI.Models.TblWestage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Bal")
                        .HasColumnName("bal")
                        .HasColumnType("float");

                    b.Property<double?>("L")
                        .HasColumnType("float");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Mid")
                        .HasColumnName("MID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Price")
                        .HasColumnName("price")
                        .HasColumnType("float");

                    b.Property<double?>("Smts")
                        .HasColumnName("smts")
                        .HasColumnType("float");

                    b.Property<double?>("Unitprice")
                        .HasColumnName("unitprice")
                        .HasColumnType("float");

                    b.Property<double?>("Units")
                        .HasColumnName("units")
                        .HasColumnType("float");

                    b.Property<double?>("W")
                        .HasColumnType("float");

                    b.Property<string>("Wrkid")
                        .HasColumnName("WRKID")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tbl_westage");
                });
#pragma warning restore 612, 618
        }
    }
}
